import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Table } from '@/components';



export default function Home({ data }: any) {
  return (
    <>
      <Head>
        <title>React Test Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Table data={data} />
      </main>
    </>
  )
}



export const getServerSideProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const result = await res.json();
  return {
    props: {
      data: result
    }
  }
}
